DROP DATABASE IF EXISTS WEB_DAY10;

CREATE DATABASE WEB_DAY10;
USE WEB_DAY10;


CREATE TABLE PASSPORTS(
	ID INT NOT NULL AUTO_INCREMENT, 
    NUMBER VARCHAR(50) UNIQUE NOT NULL, 
    PRIMARY KEY ( ID )
);

CREATE TABLE FACULTIES (
	ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(70) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE STUDENTS(
	ID INT NOT NULL AUTO_INCREMENT, 
    NAME VARCHAR(50) NOT NULL, 
    ADDRESS VARCHAR(100),
    PASSPORT_ID INT NOT NULL,
    FACULTY_ID INT NOT NULL,
    PRIMARY KEY ( ID ),
    FOREIGN KEY (PASSPORT_ID) REFERENCES PASSPORTS (ID),
    FOREIGN KEY (FACULTY_ID) REFERENCES FACULTIES (ID)
);

SELECT * FROM PASSPORTS;
SELECT * FROM FACULTIES;
SELECT * FROM STUDENTS;
