
spring:
  datasource:
    password: 12345678
    url: jdbc:mysql://localhost:3306/web_day10
    username: root
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
